version: '3.8'

volumes:
  postgres_data:
  static_data:
  media_data:
  nginx_config:

services:

  web:
    image: ashmanx/foodgram:latest
    container_name: web
    restart: always
    volumes:
      - static_data:./code/static/
      - nginx_config:./code/nginx/
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:13.1-alpine
    container_name: db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.6-alpine
    restart: always
    container_name: nginx
    volumes:
      - static_data:./code/static
      - media_data:./code/media
      - nginx_config:./code/nginx/
    ports:
      - 80:80
    depends_on:
      - web

